name: Build Shadowsocks Android AAR

on:
  push:
    branches:
      - master

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v4
        with:
          submodules: true  # 递归初始化子模块
          fetch-depth: 0     # 获取完整历史（必要时）

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build AAR
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: shadowsocks-android-aar
          path: app/build/outputs/aar/*.aar
          if-no-files-found: error
