name: Build Shadowsocks Android AAR

on:
  # 可以根据需求调整触发条件，这里设置为推送到 master 分支时触发
  push:
    branches:
      - master

jobs:
  build-aar:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 设置 Java 环境
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 赋予 gradlew 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 构建 AAR 库
      - name: Build AAR
        run: ./gradlew assembleRelease

      # 上传生成的 AAR 文件作为工件
      - name: Upload AAR
        uses: actions/upload-artifact@v3
        with:
          name: shadowsocks-android-aar
          path: app/build/outputs/aar/*.aar